# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
from PyQt5.QtGui import QPixmap
import os


class Ui_DialogAbout(object):
    def setupUi(self, DialogAbout):
        DialogAbout.setObjectName("DialogAbout")
        DialogAbout.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        DialogAbout.setWindowIcon(QtGui.QIcon("icon/ico_about.ico"))
        DialogAbout.setFixedSize(DialogAbout.sizeHint())
        DialogAbout.setStyleSheet("background-color: rgb(56, 37, 0);\n"
"color: White;")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameAbout = QtWidgets.QFrame(DialogAbout)
        self.frameAbout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAbout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAbout.setObjectName("frameAbout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameAbout)
        self.horizontalLayout.setObjectName("horizontalLayout")


        

        self.labelLogo = QLabel(self.frameAbout)
        logoPath = os.path.abspath('icon/logo.png') #иконка разработчика
        pixmap = QPixmap(logoPath)
        self.labelLogo.setPixmap(pixmap)

        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)

        self.labelLogo.setObjectName("labelLogo")
        self.horizontalLayout.addWidget(self.labelLogo)

        self.labelText = QtWidgets.QLabel(self.frameAbout)
        self.labelText.setStyleSheet("")
        self.labelText.setObjectName("labelText")
        self.horizontalLayout.addWidget(self.labelText)
        self.verticalLayout.addWidget(self.frameAbout)
        self.frameOther = QtWidgets.QFrame(DialogAbout)
        self.frameOther.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOther.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOther.setObjectName("frameOther")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameOther)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBoxOther = QtWidgets.QToolBox(self.frameOther)
        self.toolBoxOther.setObjectName("toolBoxOther")
        self.hotkey = QtWidgets.QWidget()
        self.hotkey.setGeometry(QtCore.QRect(0, 0, 521, 214))
        self.hotkey.setObjectName("hotkey")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.hotkey)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelHotKey = QtWidgets.QLabel(self.hotkey)
        self.labelHotKey.setObjectName("labelHotKey")
        self.verticalLayout_3.addWidget(self.labelHotKey)
        self.toolBoxOther.addItem(self.hotkey, "")
        self.about = QtWidgets.QWidget()
        self.about.setGeometry(QtCore.QRect(0, 0, 521, 214))
        self.about.setObjectName("about")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.about)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelAbout = QtWidgets.QLabel(self.about)
        self.labelAbout.setObjectName("labelAbout")
        self.verticalLayout_4.addWidget(self.labelAbout)
        self.toolBoxOther.addItem(self.about, "")
        self.verticalLayout_2.addWidget(self.toolBoxOther)
        self.verticalLayout.addWidget(self.frameOther)
        self.pushButtonClose = QtWidgets.QPushButton(DialogAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClose.sizePolicy().hasHeightForWidth())
        self.pushButtonClose.setSizePolicy(sizePolicy)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonClose.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.pushButtonClose.setBaseSize(QtCore.QSize(0, 0))
        self.pushButtonClose.setStyleSheet("QPushButton {background-color: rgb(51, 32, 0);\n"
"color: White;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: #382500;\n"
"padding: 4px;}\n"
"\n"
" QPushButton:pressed {background-color: rgb(46, 27, 0);\n"
"color: White;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: #241800;\n"
"padding: 4px;}")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.verticalLayout.addWidget(self.pushButtonClose)

        self.retranslateUi(DialogAbout)
        self.toolBoxOther.setCurrentIndex(0)
        self.pushButtonClose.clicked.connect(DialogAbout.close)
        QtCore.QMetaObject.connectSlotsByName(DialogAbout)

    def retranslateUi(self, DialogAbout):
        version = "21 29.10.0320"                       #версия
        developer = "2StrangerTeam"                     #разработчик
        developermail = "zerozero000one@gmail.com"     #почта разработчика
        testername = "QWERTY"                           #тестер
        testermail = "qwerty@qwerty.com"                #почта тестера
        _translate = QtCore.QCoreApplication.translate
        DialogAbout.setWindowTitle(_translate("DialogAbout", "О программе"))
        self.labelText.setText(_translate("DialogAbout", f"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Python TCP &quot;Чат комната&quot;</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Снапшот версии: </span><span style=\" font-size:11pt; color:#ffffff;\">{version}</span></p><p align=\"center\"><span style=\" color:#ffffff;\"><br/></span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Программа разработана</span><span style=\" font-size:10pt; color:#ffffff;\">: </span><span style=\" font-size:10pt; text-decoration: underline; color:#ffffff;\">{developer}</span><span style=\" font-size:10pt; color:#ffffff;\">.</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">email: </span><span style=\" font-size:9pt; color:#ffffff;\">{developermail}</span></p><p align=\"center\"><span style=\" color:#ffffff;\"><br/></span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Программа протестированна: </span><span style=\" font-size:10pt; text-decoration: underline; color:#ffffff;\">{testername}</span>.</p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">email: </span><span style=\" font-size:9pt; color:#ffffff;\">{testermail}</span></p><p><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.labelHotKey.setText(_translate("DialogAbout", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Горячие клавиши используемые по умолчанию:</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Отправка сообщения: </span><span style=\" color:#ffffff;\">Ctrl + Enter</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Копировать текст: </span><span style=\" color:#ffffff;\">Ctrl + C</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Вставить текст: </span><span style=\" color:#ffffff;\">Ctrl + V</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Вырезать текст:</span><span style=\" color:#ffffff;\"> Ctrl + X</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Выбрать всё: </span><span style=\" color:#ffffff;\">Ctrl + A</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Отменить:</span><span style=\" color:#ffffff;\"> Ctrl + Z</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Повторить:</span><span style=\" color:#ffffff;\"> Ctrl + Y</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Открыть окно параметров: </span><span style=\" color:#ffffff;\">Ctrl + P</span></p><p><span style=\" font-weight:600; color:#ffffff;\">Открыть окно &quot;О программе&quot;: </span><span style=\" color:#ffffff;\">Ctrl + I</span></p></body></html>"))
        self.toolBoxOther.setItemText(self.toolBoxOther.indexOf(self.hotkey), _translate("DialogAbout", "Горячие клавиши"))
        self.labelAbout.setText(_translate("DialogAbout", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Python TCP &quot;Чат комната&quot;</span></p><p><span style=\" color:#ffffff;\">Использует архитектуру &quot;клиент - сервер&quot;.</span></p><p><span style=\" color:#ffffff;\">Локально сохраняет &quot;Ник&quot; и историю сообщений пользователя.</span></p><p><span style=\" color:#ffffff;\">Добавлена поддержка C# клиента.</span></p><p><br/></p></body></html>"))
        self.toolBoxOther.setItemText(self.toolBoxOther.indexOf(self.about), _translate("DialogAbout", "О программе"))
        self.pushButtonClose.setText(_translate("DialogAbout", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAbout = QtWidgets.QDialog()
    ui = Ui_DialogAbout()
    ui.setupUi(DialogAbout)
    DialogAbout.show()
    sys.exit(app.exec_())
