# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from errorinput import Ui_DialogErrorInput
from errorinputsymbols import Ui_DialogErrorInputSymbols
from okdialogrename import Ui_DialogOkRename
from anyerror import Ui_DialogErrorAny
import os



class Ui_DialogRename(object):
    def setupUi(self, DialogRename):
        DialogRename.setObjectName("DialogRename")
        DialogRename.setFixedSize(588, 115)
        DialogRename.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        DialogRename.setWindowIcon(QtGui.QIcon("icon/ico_signin.ico"))
        DialogRename.setStyleSheet("background-color: rgb(61, 40, 0); color:rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogRename)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameLE = QtWidgets.QFrame(DialogRename)
        self.frameLE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLE.setObjectName("frameLE")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameLE)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditNickname = QtWidgets.QLineEdit(self.frameLE)
        self.lineEditNickname.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditNickname.setFont(font)
        self.lineEditNickname.setWhatsThis("")
        self.lineEditNickname.setStyleSheet("background-color: rgb(107, 71, 0);color:White; \n"
"border-color: rgb(85, 56, 0);\n"
"border-style: outset;")
        self.lineEditNickname.setObjectName("lineEditNickname")
        self.verticalLayout_2.addWidget(self.lineEditNickname)
        self.verticalLayout.addWidget(self.frameLE)
        self.framecButton = QtWidgets.QFrame(DialogRename)
        self.framecButton.setMinimumSize(QtCore.QSize(0, 0))
        self.framecButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framecButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framecButton.setObjectName("framecButton")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.framecButton)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonRename = QtWidgets.QPushButton(self.framecButton)
        self.pushButtonRename.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButtonRename.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0);border-style: outset; border-width: 0px;color:White;}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0);border-style: outset; border-width: 0px; color:White;}")
        self.pushButtonRename.setObjectName("pushButtonRename")
        self.horizontalLayout.addWidget(self.pushButtonRename)
        self.pushButtonExit = QtWidgets.QPushButton(self.framecButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExit.sizePolicy().hasHeightForWidth())
        self.pushButtonExit.setSizePolicy(sizePolicy)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButtonExit.setSizeIncrement(QtCore.QSize(0, 42))
        self.pushButtonExit.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0);border-style: outset; border-width: 0px;color:White;}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0);border-style: outset; border-width: 0px; color:White;}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.verticalLayout.addWidget(self.framecButton)
        self.lineEditNickname.setPlaceholderText('Введите новое имя')

        self.retranslateUi(DialogRename)
        self.pushButtonExit.clicked.connect(DialogRename.close)
        self.pushButtonRename.clicked.connect(self.signin)
        QtCore.QMetaObject.connectSlotsByName(DialogRename)


    def signin(self):                           #функция переименования
        user = self.lineEditNickname.text()

        s = "!@#№$%^&*<>-_=+]}'{[():;.,\~`/"    #запрещённые символы
        check = any(x for x in s if x in user)

        if user != "" and check == False:       #если не пустое и не имеет запрещённых символов

            currentNamef = open('users/current', 'r')
            currentName = str(currentNamef.readline().rstrip('\n'))
            currentNamef.close()

            encodeCurrentName = currentName.encode()
            decodeCurrentName = encodeCurrentName.decode('utf-8')

            check = os.path.exists(f'users/message/{decodeCurrentName}')
            if check == True:
                os.rename(f'users/message/{decodeCurrentName}', f'users/message/{user}')

            userstemp = open('users/current', 'r')      #создаёт временный файл со старым именем пользователя
            temp = open('users/temp', 'w')
            temp.write(userstemp.read())
            temp.close()
            userstemp.close()
            users = open('users/current', 'w+')          #окрывает current и вписывает новое имя
            users.write(f"{user}\n")
            users.close()
            
            self.lineEditNickname.setText('')

            

            try:
###################################################
                Form_Ok = QtWidgets.QDialog()           #вызов уведомления о успешном ренейме
                ok = Ui_DialogOkRename()
                ok.setupUi(Form_Ok)
                Form_Ok.exec_()
            except:
######################################################
                Form_Any = QtWidgets.QDialog()
                anyE = Ui_DialogErrorAny()              #диолог ошибки
                anyE.setupUi(Form_Any)
                Form_Any.exec_()


        elif check == True:
                Form_ErrorS = QtWidgets.QDialog()
                errors = Ui_DialogErrorInputSymbols()
                errors.setupUi(Form_ErrorS)
                Form_ErrorS.exec_()

        elif user == '':
                Form_Error = QtWidgets.QDialog()
                error = Ui_DialogErrorInput()
                error.setupUi(Form_Error)
                Form_Error.exec_()



    def retranslateUi(self, DialogRename):
        _translate = QtCore.QCoreApplication.translate
        DialogRename.setWindowTitle(_translate("DialogRename", "Изменение имени"))
        self.pushButtonRename.setText(_translate("DialogRename", "Переименоваться"))
        self.pushButtonExit.setText(_translate("DialogRename", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogRename = QtWidgets.QDialog()
    ui = Ui_DialogRename()
    ui.setupUi(DialogRename)
    DialogRename.show()
    sys.exit(app.exec_())