# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signinconnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from errorinput import Ui_DialogErrorInput
from errorinputsymbols import Ui_DialogErrorInputSymbols
from dialogrebootconnect import Ui_DialogReBootConn
import os

global rButton
rButton = None


class Ui_DialogConnectTo(object):
    def setupUi(self, DialogConnectTo):
        DialogConnectTo.setObjectName("DialogConnectTo")
        DialogConnectTo.setFixedSize(645, 300)
        DialogConnectTo.setWindowIcon(QtGui.QIcon("icon/ico_connect.ico"))
        DialogConnectTo.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        DialogConnectTo.setStyleSheet("background-color: rgb(56, 37, 0); color: White;")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogConnectTo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogConnectTo)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_choose = QtWidgets.QFrame(DialogConnectTo)
        self.frame_choose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choose.setObjectName("frame_choose")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_choose)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonManual = QtWidgets.QRadioButton(self.frame_choose)
        self.radioButtonManual.setObjectName("radioButtonManual")
        
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        
        self.radioButtonDefault = QtWidgets.QRadioButton(self.frame_choose)
        self.radioButtonDefault.setObjectName("radioButtonDefault")

        self.horizontalLayout_2.addWidget(self.radioButtonDefault)

        self.horizontalLayout_2.addItem(spacerItem)

        self.horizontalLayout_2.addWidget(self.radioButtonManual)

        self.verticalLayout.addWidget(self.frame_choose)
        self.frame_auto = QtWidgets.QFrame(DialogConnectTo)
        self.frame_auto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_auto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_auto.setObjectName("frame_auto")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_auto)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame_auto)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.comboBoxIPAUTO = QtWidgets.QComboBox(self.frame_auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(112)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxIPAUTO.sizePolicy().hasHeightForWidth())
        self.comboBoxIPAUTO.setSizePolicy(sizePolicy)
        self.comboBoxIPAUTO.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxIPAUTO.setSizeIncrement(QtCore.QSize(65, 0))
        self.comboBoxIPAUTO.setBaseSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBoxIPAUTO.setFont(font)
        self.comboBoxIPAUTO.setStyleSheet("background-color: rgb(83, 55, 0); color: White; selection-background-color:#8a6800; top: 1px; left: 1px;")
        self.comboBoxIPAUTO.setEditable(True)
        self.comboBoxIPAUTO.setObjectName("comboBoxIPAUTO")
        self.horizontalLayout_3.addWidget(self.comboBoxIPAUTO)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.frame_auto)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboBoxPORTAUTO = QtWidgets.QComboBox(self.frame_auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPORTAUTO.sizePolicy().hasHeightForWidth())
        self.comboBoxPORTAUTO.setSizePolicy(sizePolicy)
        self.comboBoxPORTAUTO.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBoxPORTAUTO.setFont(font)
        self.comboBoxPORTAUTO.setStyleSheet("background-color: #241800; color: White; selection-background-color:#8a6800; top: 1px; left: 1px;")

        self.comboBoxPORTAUTO.setObjectName("comboBoxPORTAUTO")
        self.horizontalLayout_3.addWidget(self.comboBoxPORTAUTO)
        self.verticalLayout.addWidget(self.frame_auto)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_IPManual = QtWidgets.QFrame(DialogConnectTo)
        self.frame_IPManual.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_IPManual.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_IPManual.setObjectName("frame_IPManual")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_IPManual)
        self.horizontalLayout_4.setContentsMargins(8, 6, 9, 6)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_IPManual)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEditONE = QtWidgets.QLineEdit(self.frame_IPManual)
        self.lineEditONE.setMaxLength(3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditONE.sizePolicy().hasHeightForWidth())
        self.lineEditONE.setSizePolicy(sizePolicy)
        self.lineEditONE.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 0px;")
        self.lineEditONE.setObjectName("lineEditONE")
        self.horizontalLayout_4.addWidget(self.lineEditONE)
        self.label_2 = QtWidgets.QLabel(self.frame_IPManual)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEditTWO = QtWidgets.QLineEdit(self.frame_IPManual)
        self.lineEditTWO.setMaxLength(3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTWO.sizePolicy().hasHeightForWidth())
        self.lineEditTWO.setSizePolicy(sizePolicy)
        self.lineEditTWO.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 0px;")
        self.lineEditTWO.setObjectName("lineEditTWO")
        self.horizontalLayout_4.addWidget(self.lineEditTWO)
        self.label_3 = QtWidgets.QLabel(self.frame_IPManual)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEditTHREE = QtWidgets.QLineEdit(self.frame_IPManual)
        self.lineEditTHREE.setMaxLength(3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTHREE.sizePolicy().hasHeightForWidth())
        self.lineEditTHREE.setSizePolicy(sizePolicy)
        self.lineEditTHREE.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 0px;")
        self.lineEditTHREE.setObjectName("lineEditTHREE")
        self.horizontalLayout_4.addWidget(self.lineEditTHREE)
        self.label_4 = QtWidgets.QLabel(self.frame_IPManual)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEditFOUR = QtWidgets.QLineEdit(self.frame_IPManual)
        self.lineEditFOUR.setMaxLength(3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFOUR.sizePolicy().hasHeightForWidth())
        self.lineEditFOUR.setSizePolicy(sizePolicy)
        self.lineEditFOUR.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 0px;")
        self.lineEditFOUR.setObjectName("lineEditFOUR")
        self.horizontalLayout_4.addWidget(self.lineEditFOUR)
        spacerItem3 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.frame_IPManual)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEditPORT = QtWidgets.QLineEdit(self.frame_IPManual)
        self.lineEditPORT.setMaxLength(5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPORT.sizePolicy().hasHeightForWidth())
        self.lineEditPORT.setSizePolicy(sizePolicy)
        self.lineEditPORT.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 0px;")
        self.lineEditPORT.setObjectName("lineEditPORT")
        self.horizontalLayout_4.addWidget(self.lineEditPORT)
        self.verticalLayout.addWidget(self.frame_IPManual)
        self.labelTAb = QtWidgets.QLabel(DialogConnectTo)
        self.labelTAb.setObjectName("labelTAb")
        
        self.verticalLayout.addWidget(self.labelTAb)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.frameButtons = QtWidgets.QFrame(DialogConnectTo)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSave = QtWidgets.QPushButton(self.frameButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("QPushButton {background-color: rgb(107, 71, 0);color:White;border-style: outset;border-width: 2px;border-radius: 15px;border-color: rgb(107, 71, 0);padding: 4px;}\n"
"QPushButton:pressed {background-color: #382500;color: White;border-style: outset;border-width: 2px;border-radius: 15px;border-color: #241800;padding: 4px;}")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonExit = QtWidgets.QPushButton(self.frameButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {background-color: rgb(107, 71, 0);color:White;border-style: outset;border-width: 2px;border-radius: 15px;border-color: rgb(107, 71, 0);padding: 4px;}\n"
"QPushButton:pressed {background-color: #382500;color: White;border-style: outset;border-width: 2px;border-radius: 15px;border-color: #241800;padding: 4px;}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.verticalLayout.addWidget(self.frameButtons)

        self.retranslateUi(DialogConnectTo)
        self.pushButtonExit.clicked.connect(DialogConnectTo.close)
        self.radioButtonDefault.clicked.connect(self.rButtonAuto)
        self.radioButtonManual.clicked.connect(self.rButtonIPManual)
        self.frame_IPManual.setDisabled(True)
        self.radioButtonDefault.setChecked(True)
        self.comboBoxIPAUTO.setEditable(False)
        self.comboBoxPORTAUTO.setEditable(False)
        self.pushButtonSave.clicked.connect(self.signconnect)
        

        self.rButtonAuto()

        self.comboBoxIPAUTO.addItem("127.0.0.1")            #Адресс по умолчанию
        self.comboBoxPORTAUTO.addItem("55555")              #Порт по умолчанию 

        checkdirIp = os.path.exists('connects/listConnectIp')
        checkdirPort = os.path.exists('connects/listConnectPort')

        if checkdirIp == True and checkdirPort == True:
            connectsIp = open('connects/listConnectIp', 'r')  #если они есть

            while True:             #цикл заполняющий комбобокс со старыми пользователями беря их из файла list построчно 
                    line = connectsIp.readline()
                    self.comboBoxIPAUTO.addItems(line.strip().splitlines())
                    if not line:
                        break
            connectsIp.close()

            connectsPort = open('connects/listConnectPort', 'r')  #если они есть

            while True:             #цикл заполняющий комбобокс со старыми пользователями беря их из файла list построчно 
                    line = connectsPort.readline()
                    self.comboBoxPORTAUTO.addItems(line.strip().splitlines())
                    if not line:
                        break
            connectsPort.close()

        QtCore.QMetaObject.connectSlotsByName(DialogConnectTo)

    def rButtonIPManual(self):

        global rButton

        self.frame_IPManual.setStyleSheet('QFrame { background-color: rgb(56, 37, 0); }')  
        self.frame_auto.setStyleSheet('QFrame { background-color: #241800; }')
        self.comboBoxPORTAUTO.setStyleSheet("background-color: #241800; color: #decdab; selection-background-color:#8a6800; top: 1px; left: 1px;")
        self.comboBoxIPAUTO.setStyleSheet("background-color: #241800; color: #decdab; selection-background-color:#8a6800; top: 1px; left: 1px;")
        self.label_7.setStyleSheet('color: #decdab')
        self.label_8.setStyleSheet('color: #decdab')
        self.frame_auto.setDisabled(True)
        self.frame_IPManual.setEnabled(True)
        self.lineEditONE.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 1px;")
        self.lineEditTWO.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 1px;")
        self.lineEditTHREE.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 1px;")
        self.lineEditFOUR.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 1px;")
        self.lineEditPORT.setStyleSheet("background-color: rgb(83, 55, 0); color: White; border: 1px;")
        self.labelTAb.setText('<html><head></head><body><center><font color = #decdab size = 2>для быстрого переключения между блоками ip-адресса используйте клавишу tab</font></center></body></html>')

        rButton = 'Manual'



    
    def rButtonAuto(self):

        global rButton

        self.frame_auto.setStyleSheet('QFrame { background-color: rgb(56, 37, 0); }')  
        self.frame_IPManual.setStyleSheet('QFrame { background-color: #241800; }')
        self.frame_IPManual.setDisabled(True)
        self.frame_auto.setEnabled(True)
        self.label_7.setStyleSheet('color: white')
        self.label_8.setStyleSheet('color: white')

        self.comboBoxPORTAUTO.setStyleSheet("background-color: rgb(83, 55, 0); color: White; selection-background-color:#8a6800; top: 1px; left: 1px;")
        self.comboBoxIPAUTO.setStyleSheet("background-color: rgb(83, 55, 0); color: White; selection-background-color:#8a6800; top: 1px; left: 1px;")

        self.lineEditONE.setStyleSheet("background-color: #1a1100; color: #decdab; border:0px;")
        self.lineEditTWO.setStyleSheet("background-color: #1a1100; color: #decdab; border:0px;")
        self.lineEditTHREE.setStyleSheet("background-color: #1a1100; color: #decdab; border:0px;")
        self.lineEditFOUR.setStyleSheet("background-color: #1a1100; color: #decdab; border:0px;")
        self.lineEditPORT.setStyleSheet("background-color: #1a1100; color: #decdab; border:0px;")
        self.labelTAb.setText('')
        
        rButton = 'Auto'

    def signconnect(self):
        global rButton

        checkdir = os.path.exists('connects')

        if checkdir == False:
            os.mkdir('connects')

        if rButton == 'Auto':
            
            ip = open('connects/currentConnectIp', 'w')
            ipCB = self.comboBoxIPAUTO.currentText()
            ip.write(ipCB)
            ip.close()
            port = open('connects/currentConnectPort', 'w')
            portCB = self.comboBoxPORTAUTO.currentText()
            port.write(portCB)
            port.close()
            
            Form_Succes = QtWidgets.QDialog()
            connect = Ui_DialogReBootConn()   #диалог удачным изменением порта и айпи
            connect.setupUi(Form_Succes)
            Form_Succes.exec_()

            QtWidgets.QApplication.quit()


        elif rButton == 'Manual':
            
            s = "!@#№$%^&*<>-_=+]}'{[():;.,\~`/"    #не допустимые символы
            ONE = str(self.lineEditONE.text())
            TWO = str(self.lineEditTWO.text())
            THREE = str(self.lineEditTHREE.text())
            FOUR = str(self.lineEditFOUR.text())
            checkONE = any(x for x in s if x in ONE)      #проверка символов
            checkTWO = any(x for x in s if x in TWO)      #проверка символов
            checkTHREE = any(x for x in s if x in THREE)      #проверка символов
            checkFOUR = any(x for x in s if x in FOUR)      #проверка символов

            if checkONE or checkTWO or checkTHREE or checkFOUR == True:
                Form_ErrorS = QtWidgets.QDialog()
                errors = Ui_DialogErrorInputSymbols()   #диалог с запрещёнными символами
                errors.setupUi(Form_ErrorS)
                Form_ErrorS.exec_()
            
            elif ONE == '' or TWO == '' or THREE == '' or FOUR == '':
                Form_Error = QtWidgets.QDialog()
                error = Ui_DialogErrorInput()   #если имя пустое диолог о заполнении
                error.setupUi(Form_Error)
                Form_Error.exec_()

            else:
                ipLE = f'{ONE}.{TWO}.{THREE}.{FOUR}'

                currentIp = open('connects/currentConnectIp', 'w')
                currentIp.write(f'{ipLE}\n')
                currentIp.close()

                ipLIST = open('connects/listConnectIp', 'a')
                ipLIST.write(f'{ipLE}\n')
                ipLIST.close()
            
            portLE = str(self.lineEditPORT.text())
            checkPORT = any(x for x in s if x in portLE)

            if portLE != '' and checkPORT == False:
                currentPORT = open('connects/currentConnectPort', 'w')
                currentPORT.write(f'{portLE}\n')
                currentPORT.close()

                portLIST = open('connects/listConnectPort', 'a')
                portLIST.write(f'{portLE}\n')
                portLIST.close()

                self.lineEditONE.setText('')
                self.lineEditTWO.setText('')
                self.lineEditTHREE.setText('')
                self.lineEditFOUR.setText('')
                self.lineEditPORT.setText('')

                Form_Succes = QtWidgets.QDialog()
                connect = Ui_DialogReBootConn()   #диалог удачным изменением порта и айпи
                connect.setupUi(Form_Succes)
                Form_Succes.exec_()

                QtWidgets.QApplication.quit()

            
            elif checkPORT == True:
                Form_ErrorS = QtWidgets.QDialog()
                errors = Ui_DialogErrorInputSymbols()   #диалог с запрещёнными символами
                errors.setupUi(Form_ErrorS)
                Form_ErrorS.exec_()
            
            elif portLE == '':
                Form_Error = QtWidgets.QDialog()
                error = Ui_DialogErrorInput()   #если имя пустое диолог о заполнении
                error.setupUi(Form_Error)
                Form_Error.exec_()

        
        



    def retranslateUi(self, DialogConnectTo):
        _translate = QtCore.QCoreApplication.translate
        DialogConnectTo.setWindowTitle(_translate("DialogConnectTo", "Соединение"))
        self.label.setText(_translate("DialogConnectTo", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Соединение</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">Пожалуйста введите IP-адресс и порт для присоеденения к серверу(или выбирите из доступных)</span></p></body></html>"))
        self.radioButtonManual.setText(_translate("DialogConnectTo", "Ручной ввод"))
        self.radioButtonDefault.setText(_translate("DialogConnectTo", "Доступные"))
        self.label_7.setText(_translate("DialogConnectTo", "IP:"))
        self.label_8.setText(_translate("DialogConnectTo", "Порт:"))
        self.label_6.setText(_translate("DialogConnectTo", "IP: "))
        self.label_2.setText(_translate("DialogConnectTo", " . "))
        self.label_3.setText(_translate("DialogConnectTo", " . "))
        self.label_4.setText(_translate("DialogConnectTo", " . "))
        self.label_5.setText(_translate("DialogConnectTo", "Порт: "))
        self.pushButtonSave.setText(_translate("DialogConnectTo", "Сохранить"))
        self.pushButtonExit.setText(_translate("DialogConnectTo", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogConnectTo = QtWidgets.QDialog()
    ui = Ui_DialogConnectTo()
    ui.setupUi(DialogConnectTo)
    DialogConnectTo.show()
    sys.exit(app.exec_())
