# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from rename import Ui_DialogRename
from settingsconnect import Ui_DialogConnectTo
from messstory import Ui_MessStory
import sys
import os

class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName("DialogSettings")
        DialogSettings.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        DialogSettings.setFixedSize(504, 474)

        DialogSettings.setWindowIcon(QtGui.QIcon("icon/ico_settings.ico"))

        DialogSettings.setStyleSheet("background-color: rgb(83, 55, 0); color: White")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSettings)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(13)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameHeader = QtWidgets.QFrame(DialogSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHeader.sizePolicy().hasHeightForWidth())
        self.frameHeader.setSizePolicy(sizePolicy)
        self.frameHeader.setStyleSheet("background-color: rgb(61, 40, 0); color:rgb(255, 255, 255);")
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameHeader)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSettings = QtWidgets.QLabel(self.frameHeader)
        self.labelSettings.setStyleSheet("")
        self.labelSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSettings.setObjectName("labelSettings")
        self.verticalLayout_2.addWidget(self.labelSettings)
        self.labelNickName = QtWidgets.QLabel(self.frameHeader)
        self.labelNickName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNickName.setObjectName("labelNickName")
        self.verticalLayout_2.addWidget(self.labelNickName)
        self.verticalLayout.addWidget(self.frameHeader)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frameAccount = QtWidgets.QFrame(DialogSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAccount.sizePolicy().hasHeightForWidth())
        self.frameAccount.setSizePolicy(sizePolicy)
        self.frameAccount.setStyleSheet("background-color: rgb(61, 40, 0); color:rgb(255, 255, 255);")
        self.frameAccount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAccount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAccount.setObjectName("frameAccount")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameAccount)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonRename = QtWidgets.QPushButton(self.frameAccount)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRename.sizePolicy().hasHeightForWidth())
        self.pushButtonRename.setSizePolicy(sizePolicy)
        self.pushButtonRename.setMinimumSize(QtCore.QSize(0, 56))
        self.pushButtonRename.setMaximumSize(QtCore.QSize(16777215, 56))
        self.pushButtonRename.setSizeIncrement(QtCore.QSize(0, 56))
        self.pushButtonRename.setBaseSize(QtCore.QSize(0, 56))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRename.setFont(font)
        self.pushButtonRename.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0); text-align: left; border-style: outset; border-width: 0px;}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0); text-align: left; border-style: outset; border-width: 0px;}")
        self.pushButtonRename.setObjectName("pushButtonRename")
        self.verticalLayout_3.addWidget(self.pushButtonRename)


        self.pushButtonConnect = QtWidgets.QPushButton(self.frameAccount)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConnect.sizePolicy().hasHeightForWidth())
        self.pushButtonConnect.setSizePolicy(sizePolicy)
        self.pushButtonConnect.setMinimumSize(QtCore.QSize(0, 56))
        self.pushButtonConnect.setMaximumSize(QtCore.QSize(16777215, 56))
        self.pushButtonConnect.setSizeIncrement(QtCore.QSize(0, 56))
        self.pushButtonConnect.setBaseSize(QtCore.QSize(0, 56))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonConnect.setFont(font)
        self.pushButtonConnect.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0); text-align: left; border-style: outset; border-width: 0px;}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0); text-align: left; border-style: outset; border-width: 0px;}")
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.verticalLayout_3.addWidget(self.pushButtonConnect)


        self.pushButtonSM = QtWidgets.QPushButton(self.frameAccount)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSM.sizePolicy().hasHeightForWidth())
        self.pushButtonSM.setSizePolicy(sizePolicy)
        self.pushButtonSM.setMinimumSize(QtCore.QSize(0, 56))
        self.pushButtonSM.setMaximumSize(QtCore.QSize(16777215, 56))
        self.pushButtonSM.setSizeIncrement(QtCore.QSize(0, 56))
        self.pushButtonSM.setBaseSize(QtCore.QSize(0, 56))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonSM.setFont(font)
        self.pushButtonSM.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0); text-align: left; border-style: outset; border-width: 0px;}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0); text-align: left; border-style: outset; border-width: 0px;}")
        self.pushButtonSM.setObjectName("pushButtonSM")
        self.verticalLayout_3.addWidget(self.pushButtonSM)
        self.verticalLayout.addWidget(self.frameAccount)



        self.frameUI = QtWidgets.QFrame(DialogSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameUI.sizePolicy().hasHeightForWidth())
        self.frameUI.setSizePolicy(sizePolicy)
        self.frameUI.setStyleSheet("background-color: rgb(61, 40, 0); color:rgb(255, 255, 255);")
        self.frameUI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUI.setObjectName("frameUI")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameUI)
        self.verticalLayout_5.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        
        self.pushButtonNoti = QtWidgets.QPushButton(self.frameUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonNoti.sizePolicy().hasHeightForWidth())
        self.pushButtonNoti.setSizePolicy(sizePolicy)
        self.pushButtonNoti.setMinimumSize(QtCore.QSize(0, 56))
        self.pushButtonNoti.setMaximumSize(QtCore.QSize(16777215, 56))
        self.pushButtonNoti.setSizeIncrement(QtCore.QSize(0, 56))
        self.pushButtonNoti.setBaseSize(QtCore.QSize(0, 56))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonNoti.setFont(font)
        self.pushButtonNoti.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0); text-align: left; border-style: outset; border-width: 0px;}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0); text-align: left; border-style: outset; border-width: 0px;}")
        self.pushButtonNoti.setObjectName("pushButtonSM")
        self.verticalLayout_5.addWidget(self.pushButtonNoti)
        
        
        self.verticalLayout.addWidget(self.frameUI)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frameSignOut = QtWidgets.QFrame(DialogSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSignOut.sizePolicy().hasHeightForWidth())
        self.frameSignOut.setSizePolicy(sizePolicy)
        self.frameSignOut.setStyleSheet("background-color: rgb(61, 40, 0); color:rgb(255, 255, 255);")
        self.frameSignOut.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSignOut.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSignOut.setObjectName("frameSignOut")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameSignOut)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButtonsignOut = QtWidgets.QPushButton(self.frameSignOut)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonsignOut.sizePolicy().hasHeightForWidth())
        self.pushButtonsignOut.setSizePolicy(sizePolicy)
        self.pushButtonsignOut.setMinimumSize(QtCore.QSize(0, 56))
        self.pushButtonsignOut.setMaximumSize(QtCore.QSize(16777215, 56))
        self.pushButtonsignOut.setSizeIncrement(QtCore.QSize(0, 56))
        self.pushButtonsignOut.setBaseSize(QtCore.QSize(0, 56))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonsignOut.setFont(font)
        self.pushButtonsignOut.setStyleSheet("QPushButton:!hover {background-color: rgb(61, 40, 0);border-style: outset; border-width: 0px;color:rgb(255, 0, 0);}\n"
"QPushButton:hover {background-color: rgb(88, 58, 0);border-style: outset; border-width: 0px; color:rgb(255, 34, 34);}")
        self.pushButtonsignOut.setObjectName("pushButtonsignOut")
        self.verticalLayout_4.addWidget(self.pushButtonsignOut)
        self.verticalLayout.addWidget(self.frameSignOut)

        userNow = open('users/current', 'r')
        nickname = str(userNow.read())
        self.labelNickName.setText(f"<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">{nickname}</span></p></body></html>")        #обновление имени в меню настроек
        userNow.close()

        self.pushButtonsignOut.clicked.connect(self.signOut)
        self.pushButtonRename.clicked.connect(self.signRename)
        self.pushButtonConnect.clicked.connect(self.connecting)
        self.pushButtonSM.clicked.connect(self.storyMess)

        self.pushButtonRename.setIcon(QIcon('icon/ico_rename.png'))
        self.pushButtonRename.setIconSize(QtCore.QSize(50,50))

        self.pushButtonConnect.setIcon(QIcon('icon/ico_settings_connect.png'))
        self.pushButtonConnect.setIconSize(QtCore.QSize(32,32))

        self.pushButtonSM.setIcon(QIcon('icon/ico_settings_sm.png'))
        self.pushButtonSM.setIconSize(QtCore.QSize(50,50))

        check = os.path.exists('users/settingFile')     #проверка файла настроек, проверяющий состояние настройки уведомления
        if check == True:
                settingFile=open('users/settingFile', 'r+')
                noti = settingFile.readline().rstrip()
                settingFile.close()
                if noti == 'Notification: True':
                        self.pushButtonNoti.setIcon(QIcon('icon/ico_notification.png'))
                        self.pushButtonNoti.setIconSize(QtCore.QSize(50,50))
                        
                elif noti == 'Notification: False':
                        self.pushButtonNoti.setIcon(QIcon('icon/ico_notification_off.png'))
                        self.pushButtonNoti.setIconSize(QtCore.QSize(50,50))
        elif check == False:
                settingFile=open('users/settingFile', 'w+')
                settingFile.write('Notification: False')
                settingFile.close()
                self.pushButtonNoti.setIcon(QIcon('icon/ico_notification_off.png'))
                self.pushButtonNoti.setIconSize(QtCore.QSize(50,50))

        self.pushButtonNoti.setText('Уведомления')
        self.pushButtonNoti.clicked.connect(self.notification)

        self.retranslateUi(DialogSettings)
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)


    def signOut(self):                  #выход с "профиля"
            QtWidgets.QApplication.closeAllWindows()
            out = open("users/out", "w")
            out.close()
            sys.exit()

    def signRename(self):               #переименование "профиля"
            Form_Signin = QtWidgets.QDialog()
            signin = Ui_DialogRename()
            signin.setupUi(Form_Signin)
            Form_Signin.exec_()
            userNow = open('users/current', 'r')
            nickname = str(userNow.read())
            self.labelNickName.setText(f"<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">{nickname}</span></p></body></html>")
            userNow.close()

    def connecting(self):         #настройки соединения
            Form_Connect = QtWidgets.QDialog()
            connect = Ui_DialogConnectTo()
            connect.setupUi(Form_Connect)
            Form_Connect.exec_()

    def storyMess(self):          #кнопка окна сохранённой истории сообщений
            Form_storyMess = QtWidgets.QDialog()
            story = Ui_MessStory()
            story.setupUi(Form_storyMess)
            Form_storyMess.exec_()

    def notification(self):     #настройки уведамлений (по умолчанию выключены)
            check = os.path.exists('users/settingFile')
            if check == True:
                settingFile=open('users/settingFile', 'r+')
                noti = settingFile.readline().rstrip()
                settingFile.close()
                if noti == 'Notification: True':

                        self.pushButtonNoti.setIcon(QIcon('icon/ico_notification_off.png'))
                        self.pushButtonNoti.setIconSize(QtCore.QSize(50,50))
                        settingFile=open('users/settingFile', 'w+')
                        settingFile.write('Notification: False')
                        settingFile.close()


                elif noti == 'Notification: False':

                        self.pushButtonNoti.setIcon(QIcon('icon/ico_notification.png'))
                        self.pushButtonNoti.setIconSize(QtCore.QSize(50,50))
                        settingFile=open('users/settingFile', 'w+')
                        settingFile.write('Notification: True')
                        settingFile.close()






    def retranslateUi(self, DialogSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSettings.setWindowTitle(_translate("DialogSettings", "Настройки"))
        self.labelSettings.setText(_translate("DialogSettings", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Настройки</span></p></body></html>"))
        self.pushButtonRename.setText(_translate("DialogSettings", "Изменить профиль"))
        self.pushButtonConnect.setText(_translate("DialogSettings", "Настройка соединения"))
        self.pushButtonSM.setText(_translate("DialogSettings", "История сообщений"))
        self.pushButtonsignOut.setText(_translate("DialogSettings", "Выйти из профиля"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    DialogSettings = QtWidgets.QDialog()
    ui = Ui_DialogSettings()
    ui.setupUi(DialogSettings)
    DialogSettings.show()
    sys.exit(app.exec_())